import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'lixivia-delicada-tanto',
    name: 'Lixívia Delicada Tanto',
    brand: 'Tanto',
    category: 'Lixívias',
    description: 'Lixívia delicada para roupas sensíveis e coloridas. Fórmula suave com poder de limpeza eficaz.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Roupas coloridas', 'Fórmula suave', 'Limpeza profunda'],
    volume: '2L',
    inStock: true
  },
  {
    id: 'lixivia-ferili-1l',
    name: 'Lixívia Ferili 1L',
    brand: 'Ferili',
    category: 'Lixívias',
    description: 'Lixívia tradicional Ferili para limpeza doméstica e desinfecção de superfícies.',
    image: 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Desinfecção doméstica', 'Branqueamento', 'Eficácia garantida'],
    volume: '1L',
    inStock: true
  },
  {
    id: 'lixivia-ferili-5l',
    name: 'Lixívia Ferili 5L',
    brand: 'Ferili',
    category: 'Lixívias',
    description: 'Lixívia Ferili em formato económico de 5 litros. Ideal para uso profissional e doméstico.',
    image: 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Formato económico', 'Uso profissional', 'Alta performance'],
    volume: '5L',
    inStock: true
  },
  {
    id: 'lixivia-pavao-5l',
    name: 'Lixívia Pavão 5L',
    brand: 'Pavão',
    category: 'Lixívias',
    description: 'Lixívia Pavão, potente e eficaz para desinfecção e limpeza profunda.',
    image: 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Potente desinfecção', 'Limpeza profunda', 'Tradição Clorosol'],
    volume: '5L',
    inStock: true
  },
  {
    id: 'lixivia-pavao-1l',
    name: 'Lixívia Pavão 1L',
    brand: 'Pavão',
    category: 'Lixívias',
    description: 'Lixívia Pavão em formato de 1 litro para uso diário.',
    image: 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Uso diário', 'Desinfecção eficaz', 'Qualidade superior'],
    volume: '1L',
    inStock: true
  },
  {
    id: 'lixivia-louro-5l',
    name: 'Lixívia Louro 5L',
    brand: 'Louro',
    category: 'Lixívias',
    description: 'Lixívia Louro com aroma fresco para uma limpeza perfumada.',
    image: 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Aroma fresco', 'Limpeza perfumada', 'Desinfecção'],
    volume: '5L',
    inStock: true
  },
  {
    id: 'super-blanch-perfumada-2l',
    name: 'Lixívia Super Blanch Perfumada 2L',
    brand: 'Super Blanch',
    category: 'Lixívias',
    description: 'Lixívia Super Blanch com perfume floral para roupas e superfícies.',
    image: 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Perfume floral', 'Branqueamento extra', 'Multiusos'],
    volume: '2L',
    inStock: true
  },
  {
    id: 'super-blanch-perfumada-4l',
    name: 'Lixívia Super Blanch Perfumada 4L',
    brand: 'Super Blanch',
    category: 'Lixívias',
    description: 'Lixívia Super Blanch Perfumada em formato familiar de 4 litros.',
    image: 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Formato familiar', 'Eficácia Super Blanch', 'Aroma duradouro'],
    volume: '4L',
    inStock: true
  },
  {
    id: 'super-blanch-tradicional-2l',
    name: 'Lixívia Super Blanch Tradicional 2L',
    brand: 'Super Blanch',
    category: 'Lixívias',
    description: 'A lixívia Super Blanch clássica para resultados impecáveis.',
    image: 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Clássica', 'Resultados impecáveis', 'Confiança'],
    volume: '2L',
    inStock: true
  },
  {
    id: 'super-blanch-tradicional-4l',
    name: 'Lixívia Super Blanch Tradicional 4L',
    brand: 'Super Blanch',
    category: 'Lixívias',
    description: 'Lixívia Super Blanch Tradicional em formato de 4 litros.',
    image: 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Económica', 'Poder branquear', 'Uso profissional'],
    volume: '4L',
    inStock: true
  },
  {
    id: 'detergente-liquido-tanto-2l',
    name: 'Detergente Líquido Tanto 2L',
    brand: 'Tanto',
    category: 'Detergentes',
    description: 'Detergente líquido para máquina de lavar roupa, eficaz na remoção de nódoas difíceis e proteção das cores.',
    image: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Limpeza profunda', 'Proteção de cores', 'Fragrância duradoura'],
    volume: '2L',
    inStock: true
  },
  {
    id: 'amaciador-tanto-2l',
    name: 'Amaciador de Roupa Tanto 2L',
    brand: 'Tanto',
    category: 'Detergentes',
    description: 'Amaciador de roupa que proporciona uma suavidade incomparável e um perfume fresco que dura todo o dia.',
    image: 'https://images.unsplash.com/photo-1558523037-299725450f61?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Suavidade extra', 'Fácil engomagem', 'Perfume fresco'],
    volume: '2L',
    inStock: true
  },
  {
    id: 'detergente-loica-tanto-1l',
    name: 'Detergente Loiça Tanto 1L',
    brand: 'Tanto',
    category: 'Detergentes',
    description: 'Detergente concentrado para lavagem manual de loiça com alto poder desengordurante e pH neutro para as mãos.',
    image: 'https://images.unsplash.com/photo-1585833014768-fb47d70b545a?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Desengordurante potente', 'Brilho intenso', 'Suave para as mãos'],
    volume: '1L',
    inStock: true
  },
  {
    id: 'lava-tudo-tanto-1-5l',
    name: 'Lava Tudo Tanto 1.5L',
    brand: 'Tanto',
    category: 'Detergentes',
    description: 'Limpador multiusos para todos os tipos de superfícies e pavimentos. Limpeza eficaz e brilho duradouro.',
    image: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Multiusos', 'Secagem rápida', 'Aroma a Limão'],
    volume: '1.5L',
    inStock: true
  },
  {
    id: 'limpa-vidros-tanto-750ml',
    name: 'Limpa Vidros Tanto 750ml',
    brand: 'Tanto',
    category: 'Detergentes',
    description: 'Solução eficaz para a limpeza de vidros, espelhos e superfícies vitrificadas. Sem deixar marcas.',
    image: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Brilho sem manchas', 'Anti-embaciamento', 'Pronto a usar'],
    volume: '750ml',
    inStock: true
  },
  {
    id: 'desengordurante-tanto-750ml',
    name: 'Desengordurante Tanto 750ml',
    brand: 'Tanto',
    category: 'Detergentes',
    description: 'Desengordurante de alta performance para cozinhas, fogões e superfícies com gordura acumulada.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Ação rápida', 'Remove gordura difícil', 'Uso em cozinhas'],
    volume: '750ml',
    inStock: true
  },
  {
    id: 'hipoclorito-sodio-5l',
    name: 'Hipoclorito de Sódio Clorosol 5L',
    brand: 'Clorosol',
    category: 'Industrial',
    description: 'Solução concentrada de hipoclorito de sódio para uso industrial e tratamento de águas.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Concentração industrial', 'Tratamento de águas', 'Desinfecção pesada'],
    volume: '5L',
    inStock: true
  },
  {
    id: 'detergente-bebe-tanto-1-5l',
    name: 'Detergente Roupa Bebé Tanto 1.5L',
    brand: 'Tanto',
    category: 'Detergentes',
    description: 'Detergente hipoalergénico especialmente formulado para a roupa delicada do bebé, dermatologicamente testado.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Hipoalergénico', 'Dermatologicamente testado', 'Sem corantes'],
    volume: '1.5L',
    inStock: true
  },
  {
    id: 'detergente-roupa-escura-tanto-1-5l',
    name: 'Detergente Roupa Escura Tanto 1.5L',
    brand: 'Tanto',
    category: 'Detergentes',
    description: 'Detergente especializado para manter a intensidade das cores escuras e pretas, prevenindo o desbotamento.',
    image: 'https://images.unsplash.com/photo-1567016376408-0226e4d0c1ea?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Proteção de cores escuras', 'Anti-desbotamento', 'Limpeza eficaz'],
    volume: '1.5L',
    inStock: true
  },
  {
    id: 'amaciador-concentrado-tanto-750ml',
    name: 'Amaciador Concentrado Tanto 750ml',
    brand: 'Tanto',
    category: 'Detergentes',
    description: 'Amaciador ultra-concentrado que proporciona uma suavidade extrema e um perfume duradouro com menos dosagem.',
    image: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Ultra-concentrado', 'Perfume premium', 'Fácil engomagem'],
    volume: '750ml',
    inStock: true
  },
  {
    id: 'pastilhas-loica-tanto-30un',
    name: 'Pastilhas Máquina Loiça Tanto (30 un)',
    brand: 'Tanto',
    category: 'Detergentes',
    description: 'Pastilhas tudo-em-um para máquina de lavar loiça, com ação desengordurante e abrilhantadora.',
    image: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Tudo-em-um', 'Poder desengordurante', 'Brilho intenso'],
    volume: '30 un',
    inStock: true
  },
  {
    id: 'desinfetante-multiusos-tanto-750ml',
    name: 'Desinfetante Multi-usos Tanto 750ml',
    brand: 'Tanto',
    category: 'Detergentes',
    description: 'Spray desinfetante sem lixívia para todas as superfícies da casa, elimina 99.9% das bactérias.',
    image: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Sem lixívia', 'Elimina bactérias', 'Aroma fresco'],
    volume: '750ml',
    inStock: true
  },
  {
    id: 'tira-noodas-tanto-500ml',
    name: 'Tira-nódoas Spray Tanto 500ml',
    brand: 'Tanto',
    category: 'Detergentes',
    description: 'Tratamento pré-lavagem eficaz contra nódoas difíceis de gordura, vinho, café e erva.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400',
    technical_sheet_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    features: ['Ação rápida', 'Eficaz em nódoas secas', 'Seguro para tecidos'],
    volume: '500ml',
    inStock: true
  }
];
